[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
derive_more = { workspace = true, features = ["display", "try_from", "from"] }
strum = { workspace = true, features = ["derive"] }
